name: Deploy to specific server

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'tests/**'
      - '**.md'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
      - uses: php-actions/composer@v6
      - name: Enter maintenance mode
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: |
            . ${{ secrets.BASH_ENV_FILE }}
            test -f ${{ secrets.DEPLOY_PATH }}/artisan && ${{ secrets.DEPLOY_PATH }}/artisan down || true
      - name: Copy files to the server
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avzr --delete --delete-excluded --include-from=.github/workflows/rsync.include --exclude-from=.github/workflows/rsync.exclude
          remote_path: ${{ secrets.DEPLOY_PATH }}
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_port: ${{ secrets.DEPLOY_PORT }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_key: ${{ secrets.DEPLOY_KEY }}
      - name: Clear cache and run migrations 
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: |
            . ${{ secrets.BASH_ENV_FILE }}
            ${{ secrets.DEPLOY_PATH }}/artisan migrate --force
            ${{ secrets.DEPLOY_PATH }}/artisan cache:clear
            ${{ secrets.DEPLOY_PATH }}/artisan up